# Pooling layer

- Average pooling

In [52]:
import numpy as np
import tensorflow as tf

layer1 = np.array([
   [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
    [[7, 7, 7], [8, 8, 8], [9, 9, 9]]],
   [[[1, 1, 1], [50, 50, 50], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
    [[7, 7, 7], [8, 8, 8], [9, 9, 9]]]
])
print(layer1.shape)
print('-' * 30)

pool1 = tf.keras.layers.GlobalAveragePooling2D()(layer1).numpy()
print(pool1)
print(pool1.shape)

(2, 3, 3, 3)
------------------------------
[[ 5  5  5]
 [10 10 10]]
(2, 3)


평균값을 반환

- Max pooling

In [49]:
layer2 = np.array([
   [[[10, 10, 1], [2, 2, 2], [4, 4, 4]], 
    [[7, 7, 7], [1, 1, 1], [60, 60, 60]],
    [[7, 7, 7], [80, 80, 80], [9, 9, 9]]],
   [[[3, 30, 30], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [60, 60, 60]],
    [[7, 7, 7], [800,800, 800], [9, 9, 9]]]
])
print(layer2.shape)
print('-' * 30)

pool2 = tf.keras.layers.MaxPooling2D(pool_size=(2,2))(layer2).numpy()
print(pool2)
print(pool2.shape)

(2, 3, 3, 3)
------------------------------
[[[[10 10  7]]]


 [[[ 5 30 30]]]]
(2, 1, 1, 3)


In [51]:
layer2 = np.array([
   [[[1, 1, 1], [2, 2, 2], [4, 4, 4]], 
    [[7, 7, 7], [1, 1, 1], [6, 6, 6]],
    [[7, 7, 7], [80, 80, 80], [9, 9, 9]]],
   [[[30, 30, 30], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
    [[7, 7, 7], [800,800, 800], [9, 9, 9]]]
])
print(layer2.shape)
print('-' * 30)

pool2 = tf.keras.layers.MaxPooling2D(pool_size=(3,3))(layer2).numpy()
print(pool2)
print(pool2.shape)

(2, 3, 3, 3)
------------------------------
[[[[ 80  80  80]]]


 [[[800 800 800]]]]
(2, 1, 1, 3)


최대값을 반환