https://wikidocs.net/105682

In [1]:
import numpy as np
import tensorflow as tf

In [6]:
layer = np.array([
    [[1, 1, 1], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
    [[7, 7, 7], [8, 8, 8], [9, 9, 9]],
])
print(layer.shape)

reshape = tf.keras.layers.Reshape(target_shape=(-1,))(layer).numpy()
print(reshape)
print(reshape.shape)

(3, 3, 3)
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]
(3, 9)


In [17]:
layer2 = np.array([
   [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
    [[7, 7, 7], [8, 8, 8], [9, 9, 9]]],
   [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]],
    [[7, 7, 7], [8, 8, 8], [9, 9, 9]]]
])
print(layer2.shape)

reshape2 = tf.keras.layers.Reshape(target_shape=(-1,))(layer2).numpy()
print(reshape2)
print(reshape2.shape)

(2, 3, 3, 3)
[[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]
 [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]]
(2, 27)


In [19]:
layer2 = np.array([
   [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]]],
   [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], 
    [[4, 4, 4], [5, 5, 5], [6, 6, 6]]]
])
print(layer2.shape)

reshape2 = tf.keras.layers.Reshape(target_shape=(2, 9))(layer2).numpy()
print(reshape2)
print(reshape2.shape)

(2, 2, 3, 3)
[[[1 1 1 2 2 2 3 3 3]
  [4 4 4 5 5 5 6 6 6]]

 [[1 1 1 2 2 2 3 3 3]
  [4 4 4 5 5 5 6 6 6]]]
(2, 2, 9)


위처럼 기존 shape형태를 유지하며 원하는 shape으로 reshape해준다.