In [1]:
import numpy as np

### numpy에서 사용하는 주요 속성  
- shape : 데이터 형태
- dtype : int64, float64 등
- size : 요소의 개수. shape의 모든 값의 곱. x.size = 3, y.size = 6 등
- ndim : 차원수. x.ndim = 1, y.ndim = 2 등. len(x.shape)과 동일
- itemsize : 요소 데이터 타입의 크기(byte 단위) x.itemsize = 8 등

- np.array array를 만드는 함수

In [2]:
arr = np.array([[2, 3, 5], [7, 4, 6]])
arr.shape

(2, 3)

numpy에서 array는 (x, y, z)가 아닌 (y, x, z)로 됨. 또는 (column, row, depth)

In [3]:
arr.size

6

In [4]:
arr.ndim

2

- np.zeros 0으로 구성된 array 만드는 함수

In [5]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- np.ones 1로 구성된 array 만드는 함수

In [6]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- np.arange(x, y, step) x부터 y전까지 step 만큼의 간격을 가진 array 생성

In [7]:
np.arange(1, 2, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

- np.linspace(x, y, n) x부터 y까지 n개의 수를 가진 array 생성

In [8]:
np.linspace(1, 10, 6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

- np.reshape array의 shape을 기존 size를 유지하면서 변경

In [9]:
ori = np.array([[1,2,3,4], [7,8,9,10], [7,6,5,4]])
ori.shape

(3, 4)

In [10]:
ori.size

12

In [11]:
reshape = np.reshape(ori, (2,6)) #또는 reshape = ori.reshape((2,6))
reshape.size

12

In [12]:
reshape

array([[ 1,  2,  3,  4,  7,  8],
       [ 9, 10,  7,  6,  5,  4]])

- astype array의 dtype을 변경

In [13]:
a = np.arange(5)
a.dtype

dtype('int32')

In [14]:
b = a.astype(float)
b.dtype

dtype('float64')

- np.where array에서 해당 인자가 어디있는지 찾기

In [15]:
a = np.array([[1,6,7], [8,3,4]])
np.where(a>5)

(array([0, 0, 1], dtype=int64), array([1, 2, 0], dtype=int64))

위 출력문의 의미는 (0, 1), (0, 2), (1, 0) 인덱스에 5보다 큰 인자가 있다는 의미이다

- np.random.rand 임의의 차원만큼의 균일분포에서 0~1사이의 랜덤한 array 생성  
- np.random.randon 용도는 같으나 parameter에 넣는 argument가 튜플형으로 들어감

In [16]:
np.random.rand(4,2,2)

array([[[0.56112771, 0.89200249],
        [0.8749321 , 0.87312345]],

       [[0.71288031, 0.66191378],
        [0.18370646, 0.86841806]],

       [[0.26424084, 0.14236024],
        [0.88318181, 0.07539474]],

       [[0.35209735, 0.07054928],
        [0.46798142, 0.35996307]]])

In [17]:
np.random.random((4,2,2)) #(4,2,2)는 error 발생

array([[[0.13571006, 0.46232532],
        [0.3959411 , 0.51820905]],

       [[0.80040959, 0.16431867],
        [0.20580419, 0.73704368]],

       [[0.44192088, 0.47210647],
        [0.95194399, 0.36326322]],

       [[0.64951262, 0.32833212],
        [0.30569359, 0.84606738]]])

- np.random.randn 평균0, 표준편차1을 가지는 표준정규분포 내에서 array 생성

In [18]:
np.random.randn(3,3)

array([[ 0.33267205,  0.69957267,  0.93723902],
       [-0.14194045, -1.03626686, -0.13187585],
       [ 0.07793211,  1.18727649, -0.19573209]])

- np.concatenate 여러 array들을 row만 맞는다면 합침

In [38]:
a = np.ones((2,2))
b = np.zeros((4,2))
c = np.array([[6,7],[4,3],[2,9],[7,7],[8,10]])

print(np.concatenate([a,b,c]))

[[ 1.  1.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 6.  7.]
 [ 4.  3.]
 [ 2.  9.]
 [ 7.  7.]
 [ 8. 10.]]
